services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: financialbudgetdb
      MYSQL_USER: financialbudgetuser
      MYSQL_PASSWORD: cadI1fzFK3t#El%I
    ports:
      - "3306:3306"
    networks:
      - personalbudget-network

  personal_budget:
    image: brunodev1988/personalbudget
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personal_budget
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_HOST: mysql
      DB_DATABASE: financialbudgetdb
      DB_USERNAME: financialbudgetuser
      DB_PASSWORD: cadI1fzFK3t#El%I
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - personalbudget-network

volumes:
  dbbase:

networks:
  personalbudget-network:
    driver: bridge