spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/financialbudgetdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: financialbudgetuser
    password: cadI1fzFK3t#El%I
    hikari:
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true

logging:
  level:
    sql: debug